name: Sync to Glitch Project

on:
  push:
    branches:
      - main
  schedule:
    # Every sixth hour
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Sync
        uses: kanadgupta/glitch-sync@main
        with:
          project-id: '${{ secrets.projectId }}'
          auth-token: '${{ secrets.authToken }}'
